apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: catastral-analyzer
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Configuración para archivos muy grandes
        run.googleapis.com/memory: "4Gi"
        run.googleapis.com/cpu: "4"
        run.googleapis.com/timeout: "900"
        run.googleapis.com/max-instances: "20"
        run.googleapis.com/execution-environment: gen2
        # Configuración para payloads ilimitados
        run.googleapis.com/cloudsql-instances: ""
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/catastral-analyzer
        ports:
        - containerPort: 8080
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: key
        resources:
          limits:
            memory: "4Gi"
            cpu: "4"
          requests:
            memory: "2Gi"
            cpu: "2"